
- name: clone murder
  git: repo=https://github.com/lg/murder.git dest=./murder
  register: clone_status
  tags: clone_murder_files

- name: rm old tgz
  shell: rm -f {{ murder_dist_tgz_file }} 
  when: clone_status.changed

- name: tar -czf
  shell: tar -czf {{ murder_dist_tgz_file }} -C ./murder/dist/ . creates={{ murder_dist_tgz_file }}
  tags: clone_murder_files

