# SCPs a compressed version of all files from ./dist (the python Bittorrent library and custom scripts) to all server.
# The entire directory is sent, regardless of the role of each individual server.
# The path on the server is specified by remote_murder_path and will be cleared prior to transferring files over.
- name: mkdir ansible_cache_path
  file: path={{ ansible_cache_path }} state=directory owner=root group=root mode=0755
  tags: distribute_files


- name: upload
  copy: src={{ murder_dist_tgz_file }} dest={{ ansible_cache_path }}/murder_dist.tar.gz
  tags: distribute_files
  register: copy_status

- name: clean up remote_murder_path
  shell: |
    [ $(find {{ remote_murder_path }}/* | wc -l ) -lt 1000 ] && 
    rm -rf {{ remote_murder_path }} || 
    ( echo 'Cowardly refusing to remove files! Check the remote_murder_path.' ; exit 1 )
  when: copy_status.changed
  register: rm_status
  tags: distribute_files

- name: dir stat
  stat: path={{ remote_murder_path }}/BitTornado
  register: st

- name: tar -xzf
  shell: mkdir -p {{ remote_murder_path }} && tar -xzf {{ ansible_cache_path }}/murder_dist.tar.gz -C {{ remote_murder_path }}
  when: st.stat.isdir is undefined
  tags: distribute_files


