
# Will cause the seeder machine to connect to the tracker and start seeding. 
# The ip address returned by the 'host' bash command will be announced to the tracker. 
# The server will not stop seeding until the stop_seeding task is called. 
# You must specify a valid 'tag' argument (which identifies the .torrent in /tmp to use)
- name: start seeding
  shell: SCREENRC=/dev/null SYSSCREENRC=/dev/null screen -dmS 'seeder-{{ tag }}' python {{ remote_murder_path }}/murder_client.py seeder '{{ filename }}.torrent' '{{ filename }}' {{ ansible_default_ipv4['address'] }}
  tags: start_seeding
