# Identical to stop_seeding, except this will kill all seeding processes. No 'tag' argument is needed."
- name: stop all seeding
  shell: pkill -f "SCREEN.*seeder-"
  register: result
  failed_when: result.rc not in [0, 1]
  changed_when: result.rc not in [0, 1]
  tags: stop_all_seeding

